.github/workflows/tests.yaml, packages/automerge-repo-network-messagechannel/package.json, packages/automerge-repo/package.json
Thought it might be useful to have a basic github action set up to run any tests on PRs and pushes to main.
Would require actions to be enabled in settings.
=> Add Tests Action

packages/automerge-repo-network-websocket/.mocharc.json, packages/automerge-repo-network-websocket/package.json, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts, packages/automerge-repo-network-websocket/test/utilities/CreateWebSocketServer.ts, packages/automerge-repo-network-websocket/test/utilities/WebSockets.ts
The message type had been commented out on the client sync message, preventing any docs from syncing
=> Fix: WebSocket Adapter

packages/automerge-repo-sync-server/package.json, packages/automerge-repo-sync-server/scripts/tests.sh, packages/automerge-repo-sync-server/src/index.js, packages/automerge-repo-sync-server/test/Server.test.js
Fixes #80 and adds a few basic tests to `automerge-repo-sync-server`
=> Add fix and tests for sync server

package.json, packages/automerge-repo-demo-counter-svelte/package.json, packages/automerge-repo-demo-counter/package.json, packages/automerge-repo-demo-todo/package.json, packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-svelte-store/src/index.ts, packages/automerge-repo-sync-server/package.json, packages/automerge-repo/README.md, packages/automerge-repo/package.json, packages/automerge-repo/src/DocHandle.ts, yarn.lock
Also updates to latest Automerge alpha
Closes #105
=> [Breaking] Change patch event signature to match automerge's patchCallback

package.json, packages/automerge-repo-network-broadcastchannel/package.json, packages/automerge-repo-network-messagechannel/package.json, packages/automerge-repo-network-websocket/package.json, packages/automerge-repo-react-hooks/package.json, packages/automerge-repo-storage-indexeddb/package.json, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-svelte-store/package.json, packages/automerge-repo/package.json, yarn.lock
Difficult to know if this takes care of all the missing deps, but it covers the ones we know about.
Closes #129
=> Try to ensure that all required deps are present

packages/automerge-repo-storage-nodefs/src/index.ts
Not sure how this one snuck past our attention, other than the obvious "I guess we're not testing the FS plugins very well" observation. This fixes #171 so thanks to @mhuangwm for reporting it.
As this is sensitive code I'd appreciate a second set of eyes before merging. @alexjg is the obvious candidate but happy for a review from anyone.
=> node-fs storage plugin: handle recursion into subdirectories for snapshots and incrementals

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/types.ts
@alexjg and maybe @HerbCaudill / @acurrieclark, I've reinstated support for clone / merge based on the underlying Automerge APIs.
Would love input on whether this is the best API for them but note that they appear to work and have tests! This was any easy one, only took me a few minutes to knock out, but I'm quite excited about using them in some upcoming projects.
=> Add support for clone and merge

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts
Fixes the problem noted in https://github.com/automerge/automerge-repo/pull/200#discussion_r1359661199
=> automerge-repo-network-websocket: actually cleanup event handlers

yarn.lock
Currently, the yarn lock file points to "http://localhost:4873" this pull request changes this back to yarnpkg.com
=> Fix yarn lock file to point to yarnpkg.com instead of localhost

packages/automerge-repo-network-messagechannel/src/StrongMessagePortRef.ts, packages/automerge-repo-network-messagechannel/src/WeakMessagePortRef.ts, packages/automerge-repo/src/helpers/pause.ts, packages/automerge-repo/src/helpers/withTimeout.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, vitest.config.ts
Adds some coverage hints, and sets the coverage output to omit files with 100% coverage.
=> Coverage config

packages/automerge-repo/test/CollectionSynchronizer.test.ts
Adapts the types in these tests to the message type changes in #250 .
=> Fix types in CollectionSynchronizer tests

packages/automerge-repo-network-websocket/README.md
We have added some optional fields and messages to the wire format of the websocket to support remote heads gossipping. Add a description of these features and specification of the wire format to the spec in `packages/automerge-repo-network-websocket`
=> Update protocol spec to include remote-heads-gossipping

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts
The websocket error handler signature is different on node and the browser
On node you get an `ErrorEvent`:
```ts
interface ErrorEvent {
error: any
message: string
type: string
target: WebSocket
}
```
In the browser you just get a generic `Event`:
```ts
interface Event {
//...
readonly srcElement: EventTarget | null
readonly target: EventTarget | null
readonly timeStamp: DOMHighResTimeStamp
readonly type: string
preventDefault(): void
stopImmediatePropagation(): void
stopPropagation(): void
//...
}
```
The `isomorphic-ws` package only gives us the node types, and our error handler for
`BrowserWebSocketClientAdapter` naïvely trusts that those types are not filthy lies. As a result
when a ws connection fails in the browser, references to `event.error.code` throw additional errors
because …
=> fix error handler in BrowserWebSocketClientAdapter

packages/automerge-repo-network-websocket/README.md
- determined by reading the WebSocket source material
=> adding documentation for the leave message

examples/react-use-awareness/package.json, examples/react-use-awareness/src/App.jsx, examples/react-use-awareness/src/main.jsx, pnpm-lock.yaml
- package.json was missing a dependency
- ran prettier throughout
=> update react-use-awareness example

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
As discussed, with a perf test. Seem reasonable to merge?
=> cache views on dochandles

packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/StorageSubsystem.test.ts
For @orionz to make docs load faster with 3.0 codebase.
=> sort snapshots to the front in loadDoc

examples/react-counter/package.json, examples/react-counter/src/App.tsx, examples/react-counter/src/main.tsx, examples/react-counter/src/shared-worker.ts, examples/react-todo/package.json, examples/react-todo/src/App.tsx, examples/react-todo/src/Todo.tsx, examples/react-todo/src/main.tsx, examples/react-todo/tailwind.config.cjs, examples/react-use-awareness/package.json, examples/react-use-awareness/src/App.jsx, examples/react-use-awareness/src/main.jsx, packages/automerge-react/README.md, packages/automerge-react/package.json, packages/automerge-react/src/index.ts, packages/automerge-react/tsconfig.json, packages/automerge-repo-react-hooks/package.json, packages/automerge-repo/src/Repo.ts, packages/automerge-vanillajs/README.md, packages/automerge-vanillajs/package.json, packages/automerge-vanillajs/src/index.ts, packages/automerge-vanillajs/tsconfig.json, packages/create-vite-app/template/package.json, packages/create-vite-app/template/src/App.tsx, packages/create-vite-app/template/src/main.tsx, pnpm-lock.yaml
I've been meaning to do this for ages, since discussing it with Anjana, and here it is. Nice simplifications in the new user experience by creating a meta-package that just reexports the bits most people will need. Trivially extended or replaced. Opinions welcome.
=> a react package for automerge-repo

packages/automerge-repo/src/index.ts
=> Add getObjectId and ObjID exports to repo

README.md, packages/automerge-repo-solid-primitives/readme.md
=> Update solid readme to point users at the correct package
