.gitignore, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo-sync-server/package.json, packages/automerge-repo-sync-server/src/index.js, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, yarn.lock
(result of me and @paulsonnentag pairing)
Reloading a client tab in Chrome creates a new peer. (Unclear if this is expected behavior?)
Previously we would see the server continue to send messages to the now-disconnected peer; thus reloading the same tab a lot would result in a lot of "phantom peers" building up.
This PR handles socket disconnection by removing the peer from the network adapter and collection/doc synchronizers.
It's been tested with a sync server running on a DigitalOcean box, when we connect a few clients and reload them a lot, we've confirmed that no messages get sent out to disconnected peers.
Questions / todos where we need more context from @pvh:
- Is it correct/reasonable to remove the peer from all synchronizers once it disconnects? Wasn't sure how long-lived peers …
=> remove peers on disconnect

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
If a document is looked for in the repo, and it exists in the `StorageAdapter`, but not in any of the peers, it is loaded correctly, but no sync messages are generated.
This pull request unblocks the `syncValue()` method, which currently waits for a `syncing` event. `incrementalLoad` only emits a `ready` event.
NB. [This test](https://github.com/pvh/automerge-repo/blob/0746eba5c9b9159f598634a9427662b2d93817fe/packages/automerge-repo/test/Repo.test.ts#L117) was already failing when I started to look at this issue
=> Add fix and test for syncValue not returning following an incremental load on an existing document

packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts
Inspired by: https://stackoverflow.com/questions/13662089/javascript-how-to-know-if-a-connection-with-a-shared-worker-is-still-alive#answer-71499332
This pull request adds a second optional parameter to the MessageChannelNetworkAdapter which allows to specify that the ports should be referenced using weak refs
```javascript
new MessageChannelNetworkAdapter(port, {useWeakRef: true}) 
```
If we use strong refs in the browser and weak refs in the shared worker inactive ports will be garbage collected eventually
=> Use weak refs so message channels of inactive tabs get garbage collected

packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/DocSynchronizer.test.ts
This PR contains a failing test to show that a peer registered with a `docSynchronizer` no longer receives sync messages if it leaves and then rejoins.
=> A peer no longer receives sync messages if it leaves and then rejoins

packages/automerge-repo/README.md
(otherwise it causes a built error)
=> fix export in example code

packages/automerge-repo-react-hooks/src/index.ts, packages/automerge-repo-react-hooks/src/types.ts, packages/automerge-repo-react-hooks/src/useDocument.ts
Fixes this build error: 
```
src/useDocument.ts(29,19): error TS2345: Argument of type 
'import("C:/git/pvh/automerge-repo/packages/automerge-repo-react-hooks/src/types").ChangeFn<T>' 
is not assignable to parameter of type 
'import("C:/git/pvh/automerge-repo/node_modules/@automerge/automerge/dist/stable").ChangeFn<T>'.
```
We were using vendored types for Automerge `Change` and `ChangeFn`: 
```ts
// types.ts (deleted)
export type ChangeFn<T> = (d: T) => void
export type Change<T> = (cf: ChangeFn<T>) => void
```
Instead we can just import these directly from Automerge: 
```ts
import { Doc, ChangeFn } from "@automerge/automerge"
```
=> Use Automerge.ChangeFn

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
When a document is created, attempting to load from storage was blocking attachment of the storage change listener.
The included test checks both that a created document can be written to immediately and that it is saved to storage such that a new repo (eg. on page refresh) can find the initial change properly.
=> Fixes saving of initial change on handle creation

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/Repo.test.ts
Currently a handle never enters the `REQUESTING` state as empty local data us automatically loaded.
This prevents an empty `Uint8Array` being loaded into a handle and switching the handle state to `READY`
=> Fix attempting to load empty data into a handle

packages/automerge-repo/package.json, packages/automerge-repo/src/DocHandle.ts
The latest automerge release has changed the `PatchCallback` contract. This amends any usage of that in `automerge-repo`
=> Update to Automerge v2.0.3

packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/StorageSubsystem.test.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts
Currently, if a document is loaded from storage, any subsequent incremental changes start again at 0. This overwrites local data.
=> Fix incremental saves following a load

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/EphemeralData.ts, packages/automerge-repo/src/index.ts
There is also the option of setting `"moduleResolution": "nodenext",` in `tsconfig` which would help enforce this, but it seems to also break some of the type imports for me in VSCode.
=> Added missing `.js` extension to a few more imports

packages/automerge-repo-demo-counter/package.json, packages/automerge-repo-demo-todo/package.json, packages/automerge-repo-sync-server/package.json, packages/automerge-repo/package.json
Some of the packages depended on out of date Automerge versions. This updates them to the same level across the monorepo
=> Update package automerge

packages/automerge-repo/README.md, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
This offers simple access to a `DocHandle`'s underlying document. There is currently no check made as to whether the document is ready, so this could return an empty doc.
=> Public API for sync access to a handle's doc

packages/automerge-repo/README.md, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
This adds a `doc`to the change event callback, allowing sync access to the latest version of the doc on each change
Closes https://github.com/automerge/automerge-repo/issues/43
=> Add doc to change event

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
As described -- we might want not to change the change signature but I think it's relatively safe?
=> Makes `change` synchronous and prevents changes during `requesting` state

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/helpers/withTimeout.ts
With `timeoutDelay` set to 700,000 ms 🤔 the tests were never finishing on their own, because the timeouts from `pause(this.#timeoutDelay)` were never cleared even if all tests completed. 
I've added a `withTimeout(p,t)` helper that takes a promise and a timeout. If the promise is resolved before the timeout ends, the timeout is cleared. If the timeout ends first, a `TimeoutError` is thrown. 
Since `DocHandle.value` and `DocHandle.loadAttemptedValue` only differ in the set of states they wait for, I've refactored the two so that the common logic isn't duplicated: 
```ts
async value(awaitStates: HandleState[] = [READY]) {
// ...
}
async loadAttemptedValue() {
return this.value([READY, REQUESTING])
}
```
=> Fix timeout implementation in DocHandle

packages/automerge-repo/src/DocHandle.ts
One more missing extension on an import
=> Fix missing `.js` extension

packages/automerge-repo/test/Repo.test.ts
This test would occasionally fail locally for me if the `docHandle was not ready. Adds an `await handle.valueI()` when needed.
=> Ensure docs are ready before changing in `syncs a bunch of changes` test

packages/automerge-repo/src/Repo.ts
`handle.request()` only changes the DocHandle's internal state. Our interest in the document is advertised by registering it with the CollectionSynchronizer.
=> Fix inaccurate comment

packages/automerge-repo-demo-counter-svelte/package.json
This package never needs to be built. Removing the build script here means that Lerna won't include it when it builds all packages, which speeds up that task.
=> Remove build script from demo-counter-svelte

LICENSE, packages/automerge-repo-demo-counter-svelte/LICENSE, packages/automerge-repo-demo-counter/LICENSE, packages/automerge-repo-demo-todo/LICENSE, packages/automerge-repo-network-broadcastchannel/LICENSE, packages/automerge-repo-network-messagechannel/LICENSE, packages/automerge-repo-network-websocket/LICENSE, packages/automerge-repo-react-hooks/LICENSE, packages/automerge-repo-storage-localforage/LICENSE, packages/automerge-repo-storage-nodefs/LICENSE, packages/automerge-repo-svelte-store/LICENSE, packages/automerge-repo-sync-server/LICENSE, packages/automerge-repo/LICENSE
None of the packages actually had a `LICENSE` file, so this adds the one used in `automerge` to all packages.
=> Add MIT license to all packages

packages/automerge-repo-sync-server/package.json, packages/automerge-repo-sync-server/src/index.js, packages/automerge-repo-sync-server/src/server.js, packages/automerge-repo-sync-server/test/Server.test.js
This refactors the sync server so that the tests should be able to run on all platforms, not just those based on *nix.
It also opens up the possibility of perhaps at some point making this importable so that a simple server could be easily customised.
Fixes #99
=> Refactored the server to allow testing on all platforms

README.md, package.json, packages/automerge-repo-network-broadcastchannel/package.json, packages/automerge-repo-network-messagechannel/package.json, packages/automerge-repo-network-websocket/package.json, packages/automerge-repo-react-hooks/README.md, packages/automerge-repo-react-hooks/package.json, packages/automerge-repo-storage-localforage/package.json, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-svelte-store/README.md, packages/automerge-repo-svelte-store/package.json, packages/automerge-repo/README.md, packages/automerge-repo/package.json
A few docs fixes following the move to the `@automerge` namespace.
This also removes a few references to the old localfirst relay network adapter which were still in the react hook, and fixes the repository entry in package.json.
=> Docs fixes

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts
The websocket adapter wraps sync messages in an envelope which looks like this:
{
senderId: string,
targetId: string,
channelId: string,
type: string,
message: UInt8Array,
broadcast: boolean,
}
The `type` field is common across all message types and is used to dispatch the message internally. In the `NodeWSServerAdapter` the type used when _sending_ a sync message was "sync", but the type expected when receiving a sync message was "message". This is because the `BrowserWebSocketClientAdapter` was sending sync messages with type "message" and didn't examine the type field at all when dispatching received sync messages. This in turn led to some confusion when implementing interoperable clients.
Modify the `BrowserWebSocketClientAdapter` to send messages with type "sync" and modify …
=> Use the same "type" for sync messages in WS client and server

packages/automerge-repo-react-hooks/src/useDocument.ts
Add the optional `ChangeOptions<T>` `options` parameter to `useDocument:changeDoc` function so it can pass it to the `DocHandle<T>:change` function.
This would be useful for example to pass along a message with the changes.
=> feat(changeDoc): add option parameter changeDoc

package.json
Added information about `yarn` version to be used.
Fixed `yarn workspace` use by prefixing workspace name with `@automerge`.
=> chore(workspaces): fix workspace invocation and fix yarn version range

packages/automerge-repo-react-hooks/package.json, packages/automerge-repo-react-hooks/src/useRepo.test.tsx, packages/automerge-repo-react-hooks/vitest.config.ts, packages/automerge-repo/package.json, yarn.lock
This PR adds tests for `useRepo`, using jsdom to mock a browser, via vitest.
=> Add automerge-repo-react-hooks tests

packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-svelte-store/src/index.ts, packages/automerge-repo/README.md, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/helpers/tests/network-adapter-tests.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/Repo.test.ts
This is a pretty big behavioural change but should work nicely for environments where the value is checked frequently. If it's only read once, the user will be confused by getting undefined back but maybe that's okay?
=> Rename `.doc` to `.syncValue` and return `undefined` when not ready

packages/automerge-repo-react-hooks/package.json
This PR fixes the test command for react-hooks, and adds it to the automated tests for the monorepo CI.
It "works fine on my machine", but I don't think I have perms to run jobs or check the output of Github actions, to confirm it actually works.
=> Fix CI tests for automerge-repo-react-hooks

.editorconfig, .eslintrc.js, examples/automerge-repo-demo-counter/src/main.tsx, packages/automerge-repo-storage-indexeddb/src/index.ts, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/storage/StorageAdapter.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/StorageSubsystem.test.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts, yarn.lock
Track the keys used to load or append to a DocHandle and then use this information to only remove keys which were used in the doc we just compacted.
=> Make storage concurrent

packages/automerge-repo-react-hooks/src/useBootstrap.ts, packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-react-hooks/src/useHandle.ts, packages/automerge-repo-svelte-store/src/index.ts, packages/automerge-repo/package.json, packages/automerge-repo/src/DocCollection.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/DocUrl.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/helpers/tests/network-adapter-tests.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/src/types.ts, packages/automerge-repo/test/CollectionSynchronizer.test.ts, packages/automerge-repo/test/DocCollection.test.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/StorageSubsystem.test.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts, yarn.lock
Here we have it -- the first draft of Automerge URLs. Most of the patch is working towards making the guts of Automerge-Repo use binary byte arrays internally. It's not "worked through" in the sense that we still have a bit of a hodgepodge of string keys for objects and byte arrays being encoded and decoded all over. But it's progress!
Key changes: `find<T>(automergeUrl: AutomergeUrl)` and `handle.url`.  Are there other places we want to expose or accept URLs at the moment? .changeAt could take a URL-with-heads for example.
=> Automerge URLs

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/test/helpers/DummyNetworkAdapter.ts
In its current form, there are no channels to join on any of the network adapters. We simply trigger the network setup using  a `join` command.
This PR keeps all the logic the same, but removes references to the concept of a `sync channel` ChannelId, as it is never referred to again.
Next step would be looking how to scope messages by `DocumentId` instead of `ChannelId` and to address the `ChannelId` used for ephemeral messaging.
=> Remove `ChannelId` from the initial NetworkSubsystem join call

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo-network-websocket/src/message.ts, packages/automerge-repo-network-websocket/src/protocolVersion.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts
This works by including a `supportedProtocolVersions` field in the join message from the client and then the server either returns a `selectedProtocolVersion` in it's `peer` message or returns a new `error` message.
Fixes #127
=> websockets: Add protocol negotiations

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/helpers/cbor.ts, packages/automerge-repo/src/index.ts
cbor-x by default tags Uint8Arrays with `64`, which is the tag from [RFC8746][1] for an array of uint8. This is a nice idea but actually really irritating when implementing an interoperable implementation on a platform which doesn't support this extension to CBOR. Disable this feature to make interoperability easier.
[1]: https://www.rfc-editor.org/rfc/rfc8746.html
=> cbor: Don't use typed array tags

packages/automerge-repo/src/DocCollection.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
Problem: currently it is possible to create a DocHandle, obtain the URl to that dochandle, and then never save anything to the dochandle (e.g. by closing the browser window) and therefore never save anything to storage. This means that you have a URL which points at a document which can _never_ be resolved. This is not a theoretical problem. In several example applications we have this pattern of creating a `DocHandle`, then immediately adding the URL to the window location. Because many of these applications don't call `DocHandle.change` until the user has pressed a button (e.g. to incrementa counter) it is possible to refresh the browser window before any call to `DocHandle.change` and end up in a situation where the `Repo` is trying to find a document which never existed.
Solution: …
=> Save documents to storage as soon as we create them

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/helpers/DummyNetworkAdapter.ts
Problem: `Repo.find` can return a `DocHandle` which is unavailable when the document is not in storage even if the document _is_ available from connected peerrs. The issue is that the network subsystem takes some time to set up connections to it's peers. For example, a `BrowserWebSocketClientAdapter` starts without a Peer ID from the server. This means that if the user requests a `DocHandle` whilst we are still waiting for the server to respond with it's peer ID then the `Repo` decides that we have no peers and consequently immediately marks the `DocHandle` as unavailable. This is bad because it's extremely surprising to the user and requires them to do awkward things like "wait ten seconds for the websocket to start up".
Solution: Add a setup phase to the `NetworkSubsystem`. Each …
=> Add a setup phase for network adapters

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/test/helpers/DummyNetworkAdapter.ts
#156 resulted in a refactor which highlighted that when we set up each network adapter, we essentially call `adapter.connect()` followed immediately by `adapter.join()`. The join is superfluous.
This also renames `leave` to disconnect and removes the unused `join` on the network subsystem.
We could also perhaps remove `leave` from the subsystem too? It isn't used anywhere yet.
=> Merge join into connect on network adapters

packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/helpers/generate-large-object.ts
This PR has 3 main effects:
1. Ensures that the first save in any handle (when the document is created) is a snapshot.
2. Checks that when a handle is deleted, snapshots and incremental saves are removed properly from storage.
3. Previously when a snapshot was being created, a subsequent change hot on the heels of it would trigger the creation of an additional snapshot, resulting in multiple snapshots in storage and slowing load times down significantly. This prevents additional snapshots being created while the storage subsystem is still creating one.
=> Fix snapshots

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-broadcastchannel/test/index.test.ts
I am using the BroadcastChannel adapter to locally sync 2 different repos managing different docs: one which only syncs locally and the other which also has a connection to the outside world. To keep the docs separate, we need separate channels.
This PR allows a `channelName` option to be passed in to the adapter construction as part of an optional `options` object.
=> Allow broadcastchannel channel name to be configured

.gitignore, examples/sync-server/.gitignore
If you run `yarn dev:demo` and add some todos, you'll end up with a bunch of files and folders in `sync-server\automerge-sync-server-data` that shouldn't make their way into source control.
=> .gitignore automerge-sync-server-data

packages/automerge-repo/src/Repo.ts
I don't know why but lines that begin with `;` upset me. 😅
=> Repo.delete: small refactoring for legibility

packages/automerge-repo-network-broadcastchannel/typedoc.json, packages/automerge-repo-network-messagechannel/typedoc.json, packages/automerge-repo-network-websocket/typedoc.json, packages/automerge-repo-react-hooks/typedoc.json, packages/automerge-repo-storage-indexeddb/typedoc.json, packages/automerge-repo-storage-nodefs/typedoc.json, packages/automerge-repo-svelte-store/typedoc.json, packages/automerge-repo/typedoc.json
VS Code tells me that this
```
"extends": "../../typedoc.base.json",
```
should be this
```
"extends": ["../../typedoc.base.json"],
```
=> typedoc.json: extends property should be array

packages/automerge-repo-network-broadcastchannel/test/index.test.ts, packages/automerge-repo/test/Repo.test.ts
Really nitpicky: 
There are a couple of spots in tests where we were rejecting with a string, e.g. `reject("c should not connect")`. I happened to break something so that one of these rejections kicked in, and was scolded in the terminal for not passing an `Error` to `reject`.
=> Reject with error

packages/automerge-repo-svelte-store/README.md, packages/automerge-repo-svelte-store/src/index.ts
Adds a second parameter to the `document` function which allows a repo to be passed in directly, rather than it being fetched from context.
Closes #172
=> Allow a specific repo to be passed in to a the svelte store

packages/automerge-repo/src/DocHandle.ts
I've never really been clear why we needed this `await pause()`, but at some point I removed it and broke blutack and so we put it back. 
It shouldn't ever really hurt anything to have an async function yield one tick, but you also shouldn't really need it. Currently tests pass with and without it. 
If this still breaks blutack, let's get to the bottom of why; and if we can't find a better solution, try to document it and get it under test.
=> DocHandle.doc(): don't yield tick

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
This removes the promise rejection when accessing `handle.doc()`, which now returns undefined on error.
Prior to this we were attempting to check for a `TimeoutError`, which was never thrown in this codepath. The state machine is set up so that it times out automatically once the `loading` or `requesting` states have been entered and the timeout period elapses.
It should be noted that the `waitFor` function will throw an error if the state machine enters a state marked as final. It was actually this error which was causing the promise to reject prior to this PR. This is used for the `whenReady` method, so it might be worth revisiting this at some point.
=> Return undefined if the document load time out

examples/react-counter/package.json, examples/react-todo/package.json, examples/react-use-awareness/package.json, examples/svelte-counter/package.json, examples/sync-server/package.json, package.json, packages/automerge-repo-network-broadcastchannel/package.json, packages/automerge-repo-network-messagechannel/package.json, packages/automerge-repo-network-websocket/package.json, packages/automerge-repo-react-hooks/package.json, packages/automerge-repo-storage-indexeddb/package.json, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-svelte-store/package.json, packages/automerge-repo/package.json, yarn.lock
This consolidates shared devDependencies into the monorepo root `package.json`. This is not strictly necessary -- they're hoisted anyway -- but it's a good practice .
=> housekeeping: clean up devDependencies

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/Repo.test.ts
This PR fixes a number of issues which are leading to apparent sync failures when the sync server is running slowly:
* Most importantly, fix a bug where an unavailable document never transition to requesting if a peer is announced on the network adapter after the document has been marked as unavilable
* Clean up event handlers on the websocket client adapter. This was causing occasional exceptions when messages arrived on the old event handlers and attempted to send messages on a new (reconnected) socket which was not ready
* Avoid decoding sync messages before sending them - this can be quite expensive
=> Some fixes

packages/automerge-repo/fuzz/fuzz.ts, packages/automerge-repo/fuzz/tsconfig.json, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/DocUrl.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/helpers/headsAreSame.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/src/synchronizer/Synchronizer.ts, packages/automerge-repo/test/CollectionSynchronizer.test.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts
I've just used VS Code's "organize imports" to remove unused imports and organize imports throughout. Also includes prettier auto-formatting in a couple of spots.
=> housekeeping: clean up imports

examples/react-use-awareness/package.json
Running `build` from the monorepo root builds all packages that have a build command. There's never any reason to build the examples, and it slows things down.
=> Remove build command from examples/react-use-awareness

packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/helpers/DummyNetworkAdapter.ts
Uses named parameters for clarity, e.g. `setup({startReady: false})` instead of `setup(false)`
Separates tests into three describe blocks, each with its own setup: 
- local only
- with peers (linear network) 
- with peers (mesh network)
Keeps everything contained within either the test closure or the setup closure, to prevent tests from stepping on each other.
=> Refactor repo tests

examples/react-counter/tsconfig.json, examples/react-todo/tsconfig.json, examples/svelte-counter/tsconfig.json
I meant to include this commit in #193. This resolves the issue with types for `useDocument` etc.
=> Set moduleResolution to Bundler in examples

package.json, vitest.config.ts, yarn.lock
To see a test coverage report in the console, use `yarn test:coverage`. 
This also adds support for the vitest UI using `yarn test:ui`:
To show coverage status directly in the source code files in VS Code, you can use the [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) extension.
=> Add support for test coverage reporting

packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts
Problem: A sync loop can be observed in the following situation:
1. A document exists on both the server and the client with divergent heads (both sides have changes the other does not have)
2. The client sends a sync message to the server
3. The server responds, but for some reason the server response is dropped
4. The client reconnects due to not receiving a response or a ping
5. The peers exchange sync messages, but the server thinks it has already sent its changes to the client, so it doesn't sent them.
6. The client notices that it doesn't have the servers changes so it asks for them
7. The server responds with an empty sync message because it thinks it has already sent the changes
6 and 7 continue in an infinite loop. The root cause is the servers failure to clear the sync state …
=> websocket: fix another sync loop

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-websocket/src/messages.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/messages.ts
`automerge-repo` currently exposes two union types for messages:
- `RepoMessage` includes all message types that a network adapter emits to the `Repo`. 
- `Message` includes all of these plus `ArriveMessage` and `WelcomeMessage`, which are message types used by some network adapters but not others. 
In anticipation of the AuthProvider work, I'm introducing an `AuthMessage` type, which doesn't fit into either of these categories: It's not `Message`, because _all_ network adapters need to be able to handle it, not just the ones that have `arrive` and `welcome`; and it's not a `RepoMessage` because it's not surfaced to the `Repo`. 
The abstract `NetworkAdapter` needs a message type that `automerge-repo` expects _every_ adapter implementation to accept, and that should be `Message`. 
This PR …
=> Remove adapter-specific message types from automerge-repo

packages/automerge-repo-storage-nodefs/src/index.ts
No changes in behavior, just some minor refactoring for clarity.
=> NodeFSStorageAdapter: refactor

packages/automerge-repo-storage-nodefs/src/index.ts
I added some `remove` tests to the storage subsystem, which promptly failed for this adapter because deleted items were still present in the cache. This PR removes deleted items from the cache before deleting them from the filesystem.
=> NodeFSStorageAdapter: remove from cache as well as file system

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/storage/StorageAdapter.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/storage/chunkTypeFromKey.ts, packages/automerge-repo/src/storage/keyHash.ts, packages/automerge-repo/src/storage/types.ts, packages/automerge-repo/test/StorageSubsystem.test.ts
This PR adds support for arbitrary key-value storage to StorageSubsystem. The `load`, `save`, and `remove` methods are for generic key/value storage, and the `loadDoc`, `saveDoc`, and `removeDoc`  methods are for Automerge documents. 
For example, these will be used by the `LocalFirstAuthProvider` to persist the encrypted team graph that encodes group membership and permissions.
```ts
const namespace = "MyCoolAdapter" 
const key = "ABC123" 
await storage.save(namespace, key, value) 
const reloadedValue = await storage.load(namespace, key) 
await storage.remove(namespace, key) 
```
The namespace parameter is to prevent collisions with other users of the storage subsystem.  Typically this will be the name of the plug-in, adapter, or other system that is using it. For example, the …
=> Add arbitrary key-value storage

packages/automerge-repo-storage-indexeddb/src/index.ts, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/storage/types.ts, packages/automerge-repo/test/StorageSubsystem.test.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts
In the process of adding a bit more test coverage to the storage system, I stumbled across a slippery little intermittent bug. This test was failing: 
https://github.com/automerge/automerge-repo/blob/f9f596a9e3589d34e7b61290697d3463152e6587/packages/automerge-repo/test/StorageSubsystem.test.ts#L43-L67
It creates 100 changes to a document in quick succession, and then immediately attempts to read the document. While that read is happening, some of those changes are still in flight, and we try to read incremental changes that have already been garbage-collected as part of the compaction process. 
There are two separate issues, and addressing either of them gets the test to pass. This PR fixes both. 
https://github.com/automerge/automerge-repo/blob/0153a67b1739412b1b26edc8a65f076adc749f07/pac …
=> StorageSubsystem: Fix bug with rapid-fire saves & concurrent reads

packages/create-repo-node-app/.eslintrc, packages/create-repo-node-app/README.md, packages/create-repo-node-app/package.json, packages/create-repo-node-app/src/index.ts, packages/create-repo-node-app/tsconfig.json
It's frequently useful to be able to quickly jump into a new project with the websocket network adapter and filesystem storage set up so that you can start experimenting with repo. This commit adds an NPM "initializer" which can be used as follows:
npm create @automerge/node-repo-app
This quickly creates an NPM package with the necessary dependencies and a simple `index.js`.
=> Add a create helper for node apps

packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts
This prevents an auth provider from sending auth messages. 
It's not the network adapter's place to have opinions about messages that it doesn't handle internally -- it should just emit them and let listeners decide what to do with them. 
It is the NetworkSubsystem's job to do this check, and it already does:
https://github.com/automerge/automerge-repo/blob/703bfa2b83fb3e04e43d856ae5f83c32670d92da/packages/automerge-repo/src/network/NetworkSubsystem.ts#L68-L72
=> BrowserWebSocketClientAdapter: Don't throw on unknown message type

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
The "failed" state is final -- it means that if we hit a timeout we give up permanently. That's not ideal because it has no path to recovery. This has been causing problems in trail-runner which has enough data that sometimes documents might take more than 60s to load, at which point no recovery is possible without killing and rebooting the service worker.
There's undoubtedly more work to do here, but by removing the "failed" state, we at least admit the possibility of recovery here.
=> remove "failed" state

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-broadcastchannel/test/index.test.ts
When I implemented this originally, I somehow managed to write a test which didn't test anything I was trying to achieve. No surprise that the feature didn't actually work.
This should remedy the issue.
=> Allow a broadcastChannel name to be properly set in the adapter

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts, packages/automerge-repo-network-websocket/src/messages.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/storage/types.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/StorageSubsystem.test.ts
- Create a stable storage ID that's generated once for each storage adapter. The sync state is persisted per storage ID. This makes the persisted sync state more useful because the same sync state can be reused even when the peer ID changes. Later this will make it also easier to assign sync state to logical entities like people and devices.
- On connect, each peer transmits:
- their peerId
- their storageId (if they have a storage adapter)
- an isEphemeral flag (sync state of ephemeral peers will not be persisted)
=> WIP: Stable peer ids

packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts
Otherwise this is a breaking change.
In the listener in `NetworkSubsystem`, defaults to false; I assume this is what we'd want.
=> Make `isEphemeral` optional in network adapter's `peer-candidate` event. 

.gitignore
- I just switched to MacOS, and suddenly I have `.DS_Store` files everywhere. 
- Also omitting the configuration file for the Wallaby test runner
=> Add a couple of things .gitignore

packages/automerge-repo/src/RemoteHeadsSubscriptions.ts, packages/automerge-repo/test/RemoteHeadsSubscriptions.test.ts
When the RemoteHeadsSubscription object receives a remote head event, it checks if the timestamp is older than the remote heads to avoid forwarding old remote heads. The problem is that if the timestamp is equal, it would also forward the remote heads. In standalone TEE, this would lead to an infinite loop of remote heads being forwarded if one document was open in the same browser on multiple tabs. This pull request fixes this so peers only forward the sync state if it's more recent.
=> Only forward sync state messages with a more recent timestamp

packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-react-hooks/src/useHandle.ts, packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useHandle.test.tsx
Previously, useDocument did not behave well for documents that took a long time to load:
1) while a load was blocking the UI, an old stale doc would be shown (potentially for multiple seconds for large docs).
2) loads that finished out of order could result in an inconsistent final state.
We have seen this cause problems in the "DocConnector" sidebar in trail-runner.
Below are demos of the two issues with a [demo app](https://github.com/inkandswitch/tiny-essay-editor/tree/knapsack/src/knapsack/components) based on the trail-runner sidebar. When you click an entry on the left, it loads a new doc URL and shows it in the main pane. The main pane shows the doc URL as well as the doc contents. (I've assigned each url a color to make visual inspection easier.)
1) stale docs during loads: while …
=> improve handling of changing URLs in useDocument and useHandle

packages/automerge-repo/README.md, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
Following discussion in #240, I thought I would add an import method to repo for adding an existing document to the repo.
Points for discussion:
1. Should the parameter be an automerge document, or a Unit8Array? I have made it a document for now, as this made most sense to me, and as it allows us to check the validity of the document and have it typed correctly.
2. What should the error message be which is thrown if an invalid document is passed in.
=> Adds `import` method to add an existing document to the repo

package.json, yarn.lock
The test runner I'm using in VS Code ([Wallaby](https://wallabyjs.com/)) supports Vitest 0.x but not the v1.0 beta. As far as I can tell there's no difference for our purposes between the beta and v0.34.
=> Upgrade Vitest to v1

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/remoteHeads.test.ts
I think we're not yet sure whether the remote heads gossiping feature is fully baked, but we have other fixes which I think we should release. Put the feature behind a feature flag so we can continue developing it on `main` without blocking release.
=> put remote heads gossiping behind a feature flag

packages/automerge-repo/README.md, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
Following up from https://github.com/automerge/automerge-repo/pull/251, this adds an export convenience method that will export a document without having to dip into automerge's `A.save()`
=> feat(automerge-repo): add export method

packages/automerge-repo-react-hooks/src/useBootstrap.ts, packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-react-hooks/src/useHandle.ts, packages/automerge-repo-react-hooks/src/useLocalAwareness.ts, packages/automerge-repo-react-hooks/src/useRemoteAwareness.ts, packages/automerge-repo-react-hooks/tsconfig.json
- On `useDocument` and `useHandle`, changes the type of the id parameter from `AutomergeUrl` to `AnyDocumentId`, since that's what `repo.find()` takes. 
- Enables strict type checking for this package, and adds/modifies types as necessary.
=> Fix types on react hooks

examples/react-counter/vite.config.ts, examples/react-todo/vite.config.ts, examples/react-use-awareness/vite.config.js, examples/svelte-counter/vite.config.ts
When starting one of the examples vite throws the following warning:
> worker.plugins is now a function that returns an array of plugins. Please update your Vite config accordingly.
This PR updates the Vite config accordingly.
=> fix: worker.plugins is now a function warning

packages/automerge-repo-react-hooks/src/index.ts, packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
replaces #196
`useDocuments` is a hook that takes a list of AutomergeUrls or DocumentIds, and maintains a map of IDs to document states. If the list of IDs changes, documents are added to or removed from the list. Document values are updated as the documents are changed in the repo. 
Includes 100% test coverage.
=> useDocuments hook

packages/automerge-repo/src/helpers/pause.ts
the function `rejectOnTimeout` isn't used anywhere in the codebase - it was supplanted by [`withTimeout`](/automerge/automerge-repo/blob/main/packages/automerge-repo/src/helpers/withTimeout.ts).
=> Remove unused function

.eslintrc.cjs, packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts, packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo/src/DocHandle.ts
Along with a few small changes to fix eslint complaints add a rule which allows unused variables in typescript files if the variable in question is prefixed with "_".
=> Appease eslint, allow deliberate unused vars

packages/automerge-repo-network-broadcastchannel/src/index.ts, packages/automerge-repo-network-broadcastchannel/tsconfig.json, packages/automerge-repo-network-messagechannel/src/index.ts, packages/automerge-repo-network-messagechannel/tsconfig.json, packages/automerge-repo-storage-indexeddb/tsconfig.json, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo-storage-nodefs/tsconfig.json, packages/automerge-repo-svelte-store/tsconfig.json, packages/automerge-repo/src/helpers/tests/network-adapter-tests.ts
Some of the network adapters were not correctly sending `peerMetadata`, nor were they properly passing the correct `peerMetadata` back to the network subsystem.
This fixes the bug and adds a test to the adapter acceptance test suite
=> Adapter peer metadata fix

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
* doc can't go from ready to unavailable state
* doc() method starts a wait promise for each awaitStates entry (`awaitStates=[ready,unavailable]` by default) 
* for ready state documents that keeps creating unnecessary timers each with 2 minute timeouts 
* for some test runners this causes node process to hang until all timers resolve. we had to add [forceExit](https://github.com/dxos/dxos/blob/main/packages/apps/composer-app/project.json#L63) in our code after migrating to automerge as tests were not exiting
=> fix: don't leave timers pending for 2 minutes on each waitForState call

packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/helpers/DummyNetworkAdapter.ts
Fixes the following case:
* Alice has a document that Bob wants to discover.
* Bob appears as a peer candidate and Alice sends a sync message.
* Bob is recorded in the list of known peers, but sync message processing fails (in the new test this happens because Alice isn't yet in the list of known peers).
* Alice appears as peer candidate but Bob decides to skip sync, because he already saw Alice (even though her document status is recorded as "has" and he doesn't have a document).
=> fix: peer doesn't receive a document on connecting with another peer

packages/automerge-repo-network-websocket/src/NodeWSServerAdapter.ts
This PR changes the `assert` import to use the local [`assert.js`](https://github.com/automerge/automerge-repo/blob/main/packages/automerge-repo-network-websocket/src/assert.ts) rather than Node's [`assert`](https://nodejs.org/api/assert.html#assert).
Node's `assert` isn't browser-compatible. 
There's normally no reason why this module should be run in the browser (although [apparently it's intended to be isomorphic](https://github.com/automerge/automerge-repo/blob/websocket-server-use-browser-compatible-assert/packages/automerge-repo-network-websocket/src/index.ts/#L10-L12)?) but I'm running into a Vite.js tree-shaking issue with [Remix in SPA mode](https://remix.run/docs/en/main/future/spa-mode), where the node websocket adapter is somehow ending up in my bundle in the browser. 
I need …
=> NodeWSServerAdapter.ts: use assert.js, not node.assert

packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
When running tests we get several copies of this warning:
```
Warning: An update to TestComponent inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at TestComponent (automerge-repo/node_modules/.pnpm/@testing-library+react@14.1.2_react-dom@18.2.0_react@18.2.0/node_modules/@testing-library/react/dist/pure.js:278:5)
at automerge-repo/packages/automerge-repo-react-hooks/test/useDocuments.test.tsx:90:37
```
This PR follows the warning's advice and wraps the stuff that causes state updates in …
=> Fix React warnings in `useDocuments` tests

packages/automerge-repo-storage-indexeddb/src/index.ts, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo/test/helpers/DummyStorageAdapter.ts
I noticed some deprecation warnings as I was doing some other work, so swapped out `extends StorageAdapter` to `implements StorageAdapterInterface` per the deprecation notes.
=> chore: update storage adapters to use interface

package.json, packages/automerge-repo-network-broadcastchannel/package.json, packages/automerge-repo-network-messagechannel/package.json, packages/automerge-repo-network-websocket/package.json, packages/automerge-repo-react-hooks/package.json, packages/automerge-repo-storage-indexeddb/package.json, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-svelte-store/package.json, packages/create-repo-node-app/package.json
This PR gets `pnpm watch` working properly. After running the script, modifying any file in the monorepo will cause the corresponding package to be rebuilt. In combination with `pnpm link`, this makes it easier to see the results of changes to this library when developing an application consuming it.
=> Fix watch scripts

packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
I started writing tests for #296, and felt the hook-testing setup could be improved.
On `renderHook`, the [testing-library docs](https://testing-library.com/docs/react-testing-library/api#renderhook) say "You should prefer `render`", and I agree. `renderHook` is a strange wrapper around `render` – there's a component being rendered behind the scenes, but the interface doesn't look like a component. I'd rather have tests that show what the hooks do in the familiar setting of a component.
Relatedly, I feel uneasy with the current testing setup because they don't prove the hooks are causing the component to re-render when docs change. It might be that the hooks return mutable objects that are mutated by some listener somewhere, causing tests to pass, without triggering component renders (as …
=> tests: start moving away from renderHook

packages/automerge-repo/src/network/NetworkAdapter.ts, packages/automerge-repo/src/network/NetworkAdapterInterface.ts
We had previously marked both the `StorageAdapter` and `NetworkAdapter` classes as deprecated. However, while the storage adapter offered no functionality, the Network adapter does offer a convenient way to include the `EventEmitter` functionality which a network adapter requires.
In the future we could likely augment the interface so that it only requires the `EventEmitter` methods we actually use (`emit` is the only one, I think), but for now the abstract class is actually useful to us and likely to others too.
=> Un-deprecate the NetworkAdapter class

packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx, packages/automerge-repo-react-hooks/test/useHandle.test.tsx, packages/automerge-repo-react-hooks/test/useRepo.test.tsx
Finishing the work started in #303; no more `renderHook`. 🙏
=> tests: finish moving away from renderHook

examples/react-counter/src/App.tsx, examples/react-counter/src/main.tsx, examples/react-todo/src/App.tsx, examples/react-todo/src/main.tsx, examples/react-use-awareness/src/App.jsx, examples/react-use-awareness/src/main.jsx
The `useBootstrap` hook is quite opinionated and a little bit magic, which makes it confusing in an example project where the goal is to understand what is going on. Switch to explicitly getting the doc URL from the url fragment or initializing it otherwise.
=> examples: Don't useBootstrap

packages/automerge-repo-network-broadcastchannel/test/index.test.ts, packages/automerge-repo-network-messagechannel/test/index.test.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts, packages/automerge-repo-storage-nodefs/package.json, packages/automerge-repo-storage-nodefs/src/index.ts, packages/automerge-repo-storage-nodefs/test/NodeFSStorageAdapter.test.ts, packages/automerge-repo-storage-nodefs/tsconfig.json, packages/automerge-repo-storage-nodefs/vitest.config.ts, packages/automerge-repo/src/helpers/tests/network-adapter-tests.ts, packages/automerge-repo/src/helpers/tests/storage-adapter-tests.ts, packages/automerge-repo/test/DummyStorageAdapter.test.ts
This test suite is based on the @acurrieclark [comment](https://github.com/automerge/automerge-repo/pull/304#issuecomment-1977446032):
> the only reason we know the existing adapters work is because we are using them in production!
To get production data, I launched the React to-do app from the example directory. I also launched the Node.js server and recorded calls to each public method of the `NodeFSStorageAdapter` instance. That recordings found its place in the test suite. I made buffers smaller for simplicity.
The reason why the storage adapter test suite function has such an interface and is used in this specific way is because I think it should be possible to execute suite hooks. For example, I think it's a good idea to clean up temp files after the execution of each test. The suit …
=> Tests suite for storage adapters

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/Repo.test.ts
Currently, there is no way to know if auto merge `Repo` finished writing all updates to disk. In our use-case, we want to know when it is safe to shut down the process (e.g. CLI) to preserve all data on disk.
related https://github.com/automerge/automerge-repo/issues/264
related [discord discussion](https://discord.com/channels/1200006940210757672/1214251439438827520)
=> feat: Add `Repo.flush` method

packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx, packages/automerge-repo-react-hooks/test/useHandle.test.tsx, packages/automerge-repo-react-hooks/test/useRepo.test.tsx
Currently useDocument doesn't listen for deletion, so docs stick around post-deletion.
(I'm not 100% sure about how deletion works, so plz lmk if this is off-base.)
=> useDocument listen to delete events

packages/automerge-repo-network-websocket/test/Websocket.test.ts, packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useHandle.test.tsx, packages/automerge-repo-react-hooks/test/useRepo.test.tsx, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/CollectionSynchronizer.test.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/Repo.test.ts, packages/automerge-repo/test/remoteHeads.test.ts
Was working on some related stuff and noticed we didn't have an API for .heads() so I added it. Didn't add a promise form... didn't feel necessary in the moment but I could do so if anyone thinks it makes sense. Tests included.
I also fixed a small annoyance en passant which I noticed while I was in there (separate patch but same PR). You can now instantiate a Repo with no config at all! No more passing in `network: []` to prevent complaints in tests.
I wanted to do a bit more about the syncState API (which is why I was in here in the first place) but I think there's a bit more of a conversation / design task to be done first so I'm going to file an issue about it and discuss there.
=> A simple heads API & optional Repo network config

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/Repo.test.ts
The `Flush` method waits for specific heads to be written on the disk, there was a race condition when you do change exactly after the `flush` heads on the disk would never be equal to the flushing heads.
This snippet shows what exactly was happening in the storage subsystem (and before this PR it would hang forever):
```ts
it.only("Flush should resolve even if doc is getting changed afterwards", async () => {
const storage = new StorageSubsystem(new NodeFSStorageAdapter())
const doc = A.change(A.init<any>(), "first change", d => {
d.foo = "bar"
})
// start flushing (with current heads).
const key = parseAutomergeUrl(generateAutomergeUrl()).documentId
const flush = storage.flush(key, doc)
// make a change (changes heads).
const changedDoc = A.change<any>(doc, "second change", d => {
d.foo …
```
=> Fix: Fix race condition in `Repo.flush` method

packages/automerge-repo/src/index.ts
In order to avoid problems created by importing mismatched versions of automerge's core CRDT library (and just the annoyance of having an extra import statement), in this PR I'm re-exporting "commonly used" Automerge types and functions.
Arguably some of these should just be better baked into DocHandle or something but I didn't want to let perfect be the enemy of good here and this is definitely an improvement.
Rarely used or more "internal" types and functions are also reexported via the AutomergeCore export which simply forwards on everything in `next` for now.
Questions for reviewers: did I miss any functions or types you commonly use? (We can always add more later.) Is there a better way to re-export this stuff? Do you hate `AutomergeCore` as the re-exported name? (I am leaning …
=> Re-export commonly used Automerge core types through Automerge Repo

packages/automerge-repo/test/Repo.test.ts
The VS Code test runner was choking on this test - not sure why, because it's syntactically valid, but upon inspection it did seem like it wasn't intended to be written the way it was. I've fixed it in a way that makes sense to me and the test runner is happy. 
before: 
```ts
expect(() => {
repo.import<TestDoc>(A.init<TestDoc> as unknown as Uint8Array)
}).toThrow()
````
after: 
```ts
expect(() => {
repo.import<TestDoc>(new Uint8Array([1, 2, 3]))
}).toThrow()
```
=> fix test: "throws an error if we try to import an invalid document"

packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
This commit fixes two bugs in the useDocuments hook, and adds corresponding tests.
1) The hook was leaking handlers and not cleaning up properly.
The useEffect teardown was trying to clean up listeners,
but the useEffect wasn't rerun when listeners were updated,
so it didn't actually work. Now we don't save listeners
in state, and instead we re-initialize them whenever the
documents list changes.
(I believe there may have been a related bug where
updates weren't being processed correctly, but I wasn't
able to get that to happen in unit tests; regardless,
I'm confident the new approach to listeners is better.)
2) The hook accepts document URLs or IDs in the list.
If URLs were passed in, updates wouldn't actually get
processed correctly because of how the internal state is
structured. Now …
=> fix bugs in useDocuments

packages/automerge-repo/src/index.ts
If the export keyword is used to export the TS type for 'Cursor', it can cause downstream TS projects using the 'isolatedModules' flag. This fixes that problem; tested by running tsc on a downstream project.
=> Use "export type" to export Cursor type

packages/automerge-repo-react-hooks/src/useDocument.ts, packages/automerge-repo-react-hooks/src/useHandle.ts, packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useHandle.test.tsx, packages/automerge-repo/src/index.ts
useDocument and useHandle had a footgun where after the input url changed, they would continue returning the old doc/handle for the previous input for 1 or more renders.
This behavior could cause problems in downstream computations or useEffect hooks which did not account for this brief inconsistency.
This patch fixes the problem by checking whether the input and output match before returning out of the hook. In useHandle we can just check the handle URL directly; in useDocument we need to store some additional state to remember the URL associated with a given doc.
- added unit tests which fail on old code and pass on new
- using these updated hooks in https://github.com/inkandswitch/tiny-essay-editor/pull/42 and it instantly solved a ton of weird bugs throughout the app
=> bugfix: avoid returning stale data in useDocument and useHandle

packages/automerge-repo/test/StorageSubsystem.test.ts
For whatever reason, the VSCode test runner doesn't see tests inside a `forEach` loop:
```ts
Object.entries(adaptersToTest).forEach(([adapterName, adapter]) => {
describe("Automerge document storage", () => {
it("stores and retrieves an Automerge document", async () => {
// ...
```
but it does if they're in a `for ... of` loop:
```ts
for (const [adapterName, adapter] of Object.entries(adaptersToTest)) {
describe("Automerge document storage", () => {
it("stores and retrieves an Automerge document", async () => {
// ...
```
=> Make VSCode test runner happy with loop in storage subsystem tests

packages/automerge-repo-react-hooks/src/useHandle.ts
Currently useHandle calls useRepo only if an id is passed in. This violates a rule of hooks that you always have to call the same hooks in the same order
=> fix useHandle to always call useRepo

packages/automerge-repo-react-hooks/README.md
Fixes the link to `useDocument.ts` in README
=> Fix link to useDocument in readme

packages/automerge-repo/src/index.ts
It's useful to have`isValidDocumentId` exposed so if we can check validity of an `id` when it comes from outside.
=> expose isValidDocumentId

packages/automerge-repo-network-websocket/src/index.ts
Hi everyone! :) Thank you for the great project.
I have noticed that the example WebSocket code doesn't work with `ProtocolV1` being exported as type:
This PR fixes that.
=> fix(websocket): ProtocolV1 shouldn't be exported as type because it's a string

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/helpers/tests/network-adapter-tests.ts, packages/automerge-repo/src/helpers/throttle.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/Repo.test.ts, pnpm-lock.yaml, vitest.config.ts
The DocHandle state machine is too complicated and too intertwingled with other systems -- DocHandles have all this responsibility to understand the network, storage, and so on.
This is the start of a de-scoping of DocHandle's responsibilities to become a much simpler wrapper around the underlying Automerge.Doc's state by giving Repo some additional responsibilities (at least in the short term).
I intend to continue down this path and simplify the state machine so it has just four states:
LOADING ---------> READY -----> DELETED
+--UNAVAILABLE+--^
This should also help with implementing an LRU cache. Alex and I discussed how we could transition a DocHandle back to LOADING and free up the doc inside. If the user requests the doc, we'd just reload / resync it (as required.) Probably more …
=> Remove isNew from DocHandle

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/network/NetworkSubsystem.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/Repo.test.ts
This removes the AWAITING_NETWORK and NETWORK_READY states from DocHandle -- instead, the Repo just waits until the networksubsystem is in a sync-able state before triggering synchronization.
Note that this patch caused me to notice (but not yet fix) a subtle problem: if you have no local data AND you try but do not succeed in connecting to the network, you will never enter "unavailable" and your handle will lurk in "loading" forever more.
I suspect we can untangle that particular problem as we go on the cleanup but I wanted to note it.
=> remove the awaiting_network states from dochandle

packages/automerge-repo/src/entrypoints/fullfat.ts
This has meant that `automerge-repo` couldn't even be _imported_ in an environment without access to `crypto.getRandomValues` (for example, outside the handler of a Cloudflare worker) because it needs to generate ids.
`init` is called correctly already any time a document is created or loaded, so this is only a bug fix and shouldn't have any other effects
=> Remove .init call from fullfat.ts

package.json, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts, pnpm-lock.yaml
Here's a test that I think exercises the bug you describe (as well as a PNPM update)... but it's passing!
I wonder if it's because IndexedDB is slower, somehow? Did I not understand the description of the bug you reported?
=> Sync bug test

packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
This is essentially the useDocuments counterpart of #318.
=> Allow useDocuments to immediately return already-loaded documents

packages/automerge-repo-network-websocket/README.md
Reading the Automerge Repo's docs I noticed what I believe is a minor discrepancy between the documented protocol and the reality as codified by the implementation:
https://github.com/automerge/automerge-repo/blob/66b09d6f3662e16e0cd8e2cafef39ef5504104d6/packages/automerge-repo-network-websocket/src/messages.ts#L18
https://github.com/automerge/automerge-repo/blob/66b09d6f3662e16e0cd8e2cafef39ef5504104d6/packages/automerge-repo-network-websocket/src/BrowserWebSocketClientAdapter.ts#L223
=> Update documentation of the wire protocol's `join` message

examples/react-todo/package.json, examples/react-todo/tailwind.config.cjs, pnpm-lock.yaml
This fixes #383.
NOTE: For some reason the `pnpm-lock.yaml` version gets upgraded from 6 to 9, although I'm using `pnpm@9.7.0` as declared in the root `package.json`:
https://github.com/automerge/automerge-repo/blob/7c486df03d5936ab0d4258040e3cc8f590967a2f/package.json#L31
=> Remove unused `@ibm/plex` dependency

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
**Summary:**
Add support for removing doc handle from handleCache to free memory, without deleting document from storage.
**Issue:**
https://github.com/automerge/automerge-repo/issues/330
**Background:**
After creating enough documents in a repo, out of memory errors will cause a synch server to crash because memory isn't being freed. Repo holds references to each DocHandle in handleCache and each DocHandle holds a reference to the automerge doc.
**Next steps:**
Once `removeFromCache` is added, it can be called from the Repo and/or synch server to free memory usage (that code must determine that the doc handle is safe to be removed from cache at that time).
=> Add support for removing doc handle from handleCache

packages/automerge-repo/src/helpers/tests/storage-adapter-tests.ts
To implement tests of a storage which use async APIs, I need the `teardown` function to be able to return a promise which gets awaited. I also took the liberty to refactor the tests a bit to use a `beforeEach` hook instead of calling `setup` and `teardown` in each of the tests. This ensures the `teardown` gets called even if the test fails. In the current state, this isn't the case since something throwing in the test could prevent the call to `teardown`.
=> Refactor the storage adapter tests to use a `beforeEach` hook

examples/sync-server/index.js, examples/sync-server/package.json, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/synchronizer/CollectionSynchronizer.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/src/synchronizer/Synchronizer.ts, pnpm-lock.yaml
Problem: when analyzing a sync server under heavy load it is difficult
to identify what is causing the load. There are lots of questions we
might have such as "what documents are in memory?" or "which documents are
taking longest  in `receiveSyncMessage`?". 
Solution: expose a `"doc-metrics"` event on `Repo` which is fired
whenever a documnt is loaded or receives a sync message. This can be
wired up to Prometheus or other monitoring tools to allow operators to
answer these questions.
=> Repo per doc metrics

packages/automerge-repo-react-hooks/src/useDocuments.ts
Right now, useDocuments tries to memoize the list of ids/urls argument as it normalizes it to ids to avoid doing unnecessary work if the list is not changing. However, it does this by passing the ids as a member of the useMemo dependencies array. If callers are passing the array as a literal, this will create a new array on every render, and the memoization won't accomplish anything.
To avoid this, we could spread the array to add its members (the real dependencies) to our useMemo dependencies, but since there are no other dependencies, we can pass the ids array itself instead.
=> Fix memoization of ids in useDocuments.ts

packages/automerge-repo/src/helpers/tests/storage-adapter-tests.ts
This PR is more a question then a suggestion.
The question: should we care about an order in which `StorageAdapterInterface.loadRange` returns data?
When I utilized `expect.arrayContaining` in this commit https://github.com/bijela-gora/automerge-repo/commit/3238d7a6e2a7f8563aed17b554996c3c329894a8 to automerge-repo I'm sure I didn't consider that. Now, I'm not even sure why I used that asymmetric matcher. The `expect.arrayContaining` does not care about an order of elements inside arrays:
```javascript
describe('expect.arrayContaining', () => {
it("doesn't care about order", () => {
expect([0, 1, 2]).toEqual(expect.arrayContaining([2, 0]))
})
})
```
I noticed that a day ago when I was trying to make a storage adapter based on `node:sqlite`. For some reasons `better-sqlite3` and …
=> Slightly improved tests for loadRange method

packages/automerge-repo/src/AutomergeUrl.ts, packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/RemoteHeadsSubscriptions.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/helpers/bufferFromHex.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/test/AutomergeUrl.test.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/DocSynchronizer.test.ts, packages/automerge-repo/test/Repo.test.ts, pnpm-lock.yaml
Long promised, finally implemented. Here's a patch that adds support for heads in URLs. They look a bit like this right now:
`automerge:2B7BMuPYXrj5wA9P2mjnKDtWhDwD#3h6NoQHYgGneicxivqye6vA4PqSA`
You can find, clone, and diff DocHandles that include their heads URLs. Changing documents identified by their heads is not supported (use changeAt on the main document handle without heads.)
Some design notes: the individual URL components are each bs58check encoded. This is wasteful but felt consistent. Designing a way to encode an array of heads into one bs58check encoded block was beyond my creativity today, and I felt like being able to see the individual components is worthwhile.
Internally, automerge uses hex-encoded hashes for heads. For consistency with documentIds (and compactness), I …
=> Support for heads in Automerge urls

examples/react-counter/src/shared-worker.ts, examples/react-todo/src/main.tsx, examples/svelte-counter/src/App.svelte, examples/sync-server/index.js, packages/automerge-repo-network-websocket/src/WebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/src/WebSocketServerAdapter.ts, packages/automerge-repo-network-websocket/src/index.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts, packages/automerge-repo/README.md, packages/create-repo-node-app/src/index.ts, packages/create-vite-app/template/src/main.tsx, pnpm-lock.yaml
The old names are preserved for backwards compatibility via hidden exports. I didn't add "Network" to the name (which would be more consistent) but WebSocketClientNetworkAdapter is such a finger-full... does anyone have opinions?
=> rename poorly named WebSocket packages

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/src/index.ts, packages/automerge-repo/src/storage/StorageSubsystem.ts, packages/automerge-repo/src/storage/keyHash.ts, packages/automerge-repo/src/synchronizer/DocSynchronizer.ts, packages/automerge-repo/test/DocHandle.test.ts, packages/automerge-repo/test/StorageSubsystem.test.ts
In the upcoming Automerge 3.0 there is no `/next` subpath export and the `next` interface is deprecated. We want to continue working with both Automerge 3.0 and Automerge 2.0, so we switch to using `next` like this:
import { next as Automerge } from "@automerge/automerge"
This will be backwards compatible with both versions of Automerge
=> Don't use `/next` subpath export from `@automerge/automerge`

packages/automerge-repo-react-hooks/test/testSetup.ts, packages/automerge-repo-react-hooks/test/testSetup.tsx, packages/automerge-repo-react-hooks/test/useDocHandle.test.tsx, packages/automerge-repo-react-hooks/test/useDocument.test.tsx, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx, packages/automerge-repo-react-hooks/vitest.config.ts
In updating the tests for #429, I found that we have very similar
setup code in three hook test files. There are some benefits to
localized setup like that, but I can't imagine our tests for this
package will ever care very much about the actual document contents,
so instead of copying the paired repo setup code to yet another place,
I decided to try refactoring.
Thoughts?
=> Refactor automerge-repo-react-hooks test setup code

packages/automerge-repo-react-hooks/src/useDocHandles.ts, packages/automerge-repo-react-hooks/src/useDocuments.ts, packages/automerge-repo-react-hooks/test/useDocuments.test.tsx
Allow useDocuments and useDocHandles to immediately return
already-loaded documents without invoking Suspense (in their Suspense
variants).
We should avoid unnecessary Suspense since it can lead to clumsy UX
with flashing loaders.
See also #415.
=> automerge-repo-react-hooks: avoid Suspense where possible for useDocuments

packages/automerge-repo/src/index.ts
The `RawString` and `ImmutableString` symbols that are exported by `automerge-repo` only work as values since version 2, as reported in #437.
This PR fixes this bug by exporting separate types that have the same name and are defined as `InstanceType<typeof Automerge.RawString>`.
=> Export explicit RawString and ImmutableString types (fix #437)

packages/automerge-repo/src/DocHandle.ts, packages/automerge-repo/test/DocHandle.test.ts
We currently only support one way of putting a docHandle into readOnly mode, which is to view at particular point in time in the past. This is occasionally requested functionality though, so in preparation for introduction of Keyhive ACLs and other similar work, I've taken the liberty of introducing a new test function here.
=> isReadOnly() -- test if a dochandle can be change()d

packages/automerge-repo-network-websocket/src/WebSocketClientAdapter.ts, packages/automerge-repo-network-websocket/test/Websocket.test.ts
Problem: If the server sends invalid CBOR then the client will crash and bring down the whole repo with it. 
Solution: catch the error in the client and log it, then rely on the normal reconnect logic to recover (in case the server is just temporarily misbehaving).
=> automerge-repo-network-websocket: handle invalid cbor in the client

packages/automerge-react/package.json, packages/automerge-repo-react-hooks/package.json
To avoid this warning:
```
 WARN  Issues with peer dependencies found
└─┬ @automerge/automerge-repo-react-hooks 2.0.6
├── ✕ unmet peer react@^18.0.0: found 19.1.0
└── ✕ unmet peer react-dom@^18.0.0: found 19.1.0
```
=> allow react 19

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
Problem:
https://github.com/automerge/automerge-repo/issues/456
Proposed solution:
In Repo.ts, since `#registerHandleWithSubsystems` can be called multiple times, check existing listeners on the handle before adding a listener for the save function.
=> Prevent duplicate save listeners

packages/automerge-repo-bundles/README.md, packages/automerge-repo-bundles/package.json, packages/automerge-repo-bundles/src/bufferFromHex.ts, packages/automerge-repo-bundles/src/index.ts, packages/automerge-repo-bundles/test/bundles.test.ts, packages/automerge-repo-bundles/tsconfig.json, packages/automerge-repo-bundles/vitest.config.ts, packages/automerge-repo/src/Repo.ts, packages/automerge-repo/src/index.ts, pnpm-lock.yaml
Problem: there are many usecases where it would be useful to be able to transfer a set of documents from one repo to another without having a direct connection between them. Some important usecases are initializing an application with some shared document history and sync-via-email. At the moment this is not possible. Even though the underlying automerge document can be saved to a binary format, automerge-repo provides no APIs for importing such a binary file into an existing document without first finding that document somewhere.
The reason we have not added this import feature to date is that allowing the user to set the document ID for some arbitrary document is a giant footgun. It allows users to create documents which are unrelated to each other but have the same ID, which generally …
=> Add the ability to export a bundle of documents from a Repo

packages/automerge-repo-solid-primitives/package.json
As it stands, I get this warning when installing `automerge-repo-solid-primitives`:
```
 WARN  Issues with peer dependencies found
.
└─┬ @automerge/automerge-repo-solid-primitives 2.3.1
└── ✕ unmet peer @automerge/automerge@3.0.0: found 3.1.1
```
=> Overly strict peer dependency in solid primitives

packages/automerge-repo/src/Repo.ts, packages/automerge-repo/test/Repo.test.ts
Problem: in 722a48f9 we added an experimental constructor argument to Repo which allowed the user to provide a function used to generate new document IDs. The purpose of this function was so that keyhive can provide the IDs for documents, which in turn means that we don't have to carry around a mapping of keyhive IDs to document IDs in keyhive applications. Unfortunately it turns out that the keyhive ID generation is asynchronous, which means that we can't call it in Repo.create.
Solution: add a new method Repo.create2 which is asynchronous and which calls the id generator if present. This method is hidden and experimental. Long term I think we will need to do a major version change for Repo and make Repo.create asynchronous, but for now we can experiment with create2
=> Add Repo.create2 to allow asynchronous id generation
